import {chromium} from '@playwright/test';
const browser=await chromium.launch();
const page=await browser.newPage({viewport:{width:1440,height:1080},deviceScaleFactor:1});
await page.goto('http://localhost:3000');
await page.screenshot({path:'../docs/screenshots/desktop-initial.png',fullPage:true});
console.log({title:await page.title(),overflow:await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)});
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'../docs/screenshots/mobile-initial.png',fullPage:true});
console.log({mobileOverflow:await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)});
await browser.close();
