import { chromium } from '@playwright/test';
const browser = await chromium.launch();
const page = await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:3000');
await page.locator('.find-button').click();
await page.locator('.mode-notice').waitFor({timeout:180000});
const label=await page.locator('.mode-notice').innerText();
if(!label.includes('Investigated by your local Ollama agent'))throw new Error(label);
const cards=await page.locator('.event-card').count();
if(cards!==3)throw new Error(`Expected 3 recommendations; received ${cards}`);
await page.locator('.results-section').screenshot({path:'../docs/screenshots/desktop-agent-results.png'});
await page.locator('.primary-card').getByRole('button',{name:'Know before you go'}).click();
await page.screenshot({path:'../docs/screenshots/desktop-agent-guide.png'});
await page.getByRole('button',{name:'Close guide'}).click();
await page.setViewportSize({width:390,height:844});
await page.locator('.results-section').screenshot({path:'../docs/screenshots/mobile-agent-results.png'});
if(errors.length)throw new Error(errors.join('\n'));
console.log(JSON.stringify({agentActive:true,cards,errors,title:await page.title()}));
await browser.close();
